introproventures/graphql-jpa-query

- .codecov.yml
- .travis.yml
- README.md
> Add codecov.io integration with Travis-CI

- .gitignore
- README.md
- graphql-jpa-query-annotations/.project
- graphql-jpa-query-boot-starter/.classpath
- graphql-jpa-query-boot-starter/.project
- graphql-jpa-query-example/.project
- graphql-jpa-query-schema/.project
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaExecutor.java
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/QraphQLJpaBaseDataFetcher.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/JavaScalarsTest.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/StarwarsQueryExecutorTests.java
> Implemented support for parameter bindings in reverse queries

- graphql-jpa-query-boot-starter/.project
- graphql-jpa-query-example/.project
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaOneToManyDataFetcher.java
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaQueryDataFetcher.java
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/QraphQLJpaBaseDataFetcher.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/StarwarsQueryExecutorTests.java
> Handle orderBy in nested queries

- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/JpaPredicateBuilder.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/StarwarsQueryExecutorTests.java
> Fix: 'NE' is generating 'LIKE' statement instead of notEqual for Strings

- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaSchemaBuilder.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/GraphQLExecutorTests.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/model/book/Author.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/model/book/Book.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/model/book/Genre.java
- graphql-jpa-query-schema/src/test/resources/data.sql
> Support @ElementCollection attribute mappings

- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/JpaPredicateBuilder.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/GraphQLExecutorTests.java
Currently UUIDs only work as primary key attributes. Using them in a CriteriaExpression runs into the following issue however. For Example running:
<details><summary>Kotlin Entity</summary>
<p>
```Event.kt
@Entity
class Event(
@Id
val id: UUID? = null,
) {
}
```
</p>
</details>
<details><summary>Query</summary>
<p>
```
{
Events(where: {id: {EQ: "11781ee7-591f-4a7f-819d-07e12eedbe65"}}) {
select {
id
}
}
}
```
</p>
</details>
<details><summary>Result</summary>
<p>
```response.json
{
"data": {},
"errors": [
{
"message": "Exception while fetching data (/Events) : Unsupported field type class java.util.UUID for field id",
"path": [
"Events"
],
"exception": {
"stackTrace": [
{
"methodName": "getTypedPredicate",
"fileName": "JpaPredicateBuilder.java",
"lineNumber": 327,
"className": …
```
> Fix generated CriteriaExpression not working with UUIDs

- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaSchemaBuilder.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/GraphQLExecutorTests.java
Hi,
Some minor changes to implement your TODO test queryForEntityWithEmeddableTypeAndWhere.
> query for entity with emeddableType and where argument

- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/JpaPredicateBuilder.java
This PR adds missing equal SQL predicate for string arguments in where criteria expressions
> fix: add missing equal criteria expression for string arguments

- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/JavaScalars.java
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaQueryDataFetcher.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/JavaScalarsTest.java
> Add Missing LocalTime Coercing 

- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaSchemaBuilder.java
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/JpaPredicateBuilder.java
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/PredicateFilter.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/GraphQLExecutorTests.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/StarwarsQueryExecutorTests.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/model/book/Book.java
- graphql-jpa-query-schema/src/test/resources/data.sql
> feat:  BETWEEN and NOT_BETWEEN where criterias

- graphql-jpa-query-autoconfigure/.classpath
- graphql-jpa-query-autoconfigure/pom.xml
- graphql-jpa-query-autoconfigure/src/main/java/com/introproventures/graphql/jpa/query/autoconfigure/GraphQLSchemaAutoConfiguration.java
- graphql-jpa-query-autoconfigure/src/main/java/com/introproventures/graphql/jpa/query/autoconfigure/GraphQLSchemaConfigurer.java
- graphql-jpa-query-autoconfigure/src/main/java/com/introproventures/graphql/jpa/query/autoconfigure/GraphQLSchemaFactoryBean.java
- graphql-jpa-query-autoconfigure/src/main/java/com/introproventures/graphql/jpa/query/autoconfigure/GraphQLShemaRegistration.java
- graphql-jpa-query-autoconfigure/src/main/resources/META-INF/spring.factories
- graphql-jpa-query-autoconfigure/src/test/java/com/introproventures/graphql/jpa/query/autoconfigure/GraphQLSchemaAutoConfigurationTest.java
- graphql-jpa-query-boot-starter/pom.xml
- graphql-jpa-query-boot-starter/src/main/java/com/introproventures/graphql/jpa/query/boot/autoconfigure/GraphQLJpaQueryAutoConfiguration.java
- graphql-jpa-query-dependencies/pom.xml
- pom.xml
> feat: Let's try GraphQL Schema Autoconfiguration with stitching several schemas together

- graphql-jpa-query-annotations/src/main/java/com/introproventures/graphql/jpa/query/annotation/GraphQLDescription.java
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaSchemaBuilder.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/StarwarsSchemaBuildTest.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/model/starwars/CodeList.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/model/starwars/Droid.java
Allow the @GraphQLDescription to be placed on getter methods as well as fields, and search for it if it is in a different place to the JPA annotations.
As well as allowing flexibility in developer's/teams preferences this enables support for Entity generation tools such as HibernateTools.
> Flexible description annotation

- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaSchemaBuilder.java
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaSimpleDataFetcher.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/GraphQLExecutorTests.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/model/embedded/Boat.java
- graphql-jpa-query-schema/src/test/resources/data.sql
This is a new feature PR to support JPA @EmbeddedId attribute mappings submitted by @ludovicmotte,
Given, the following entity class definition with `@EmbeddableId` :
```java
@Entity(name = "Boat")
@Data
public class Boat  {
@Embeddable
@Data
public static class BoatId implements Serializable {
private static final long serialVersionUID = 1L;
String id;
String country;
}
@EmbeddedId
@GraphQLDescription("Primary Key for the Boat Class")
BoatId boatId;
@Embedded
Engine engine;
}
```
Will generate schema to query entities using embedded id attributes:
Singular Query Field: 
```
query { 
Boat( boatId: { id: "1" country: "EN" } ) { 
boatId { 
id country 
} 
engine { 
identification 
} 
} 
}
```
Plural Query Field: 
```
query { 
Boats { 
select { 
boatId( where: { id: { EQ: "1"} country: { EQ: …
```
> feat: add JPA @EmbeddedId support

- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/CashGraphQLCalculatedFields.java
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaSchemaBuilder.java
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/QraphQLJpaBaseDataFetcher.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/CalcEntityTests.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/model/calc/CalcEntity.java
- graphql-jpa-query-schema/src/test/resources/data.sql
continue https://github.com/introproventures/graphql-jpa-query/pull/83
> Implementation calculations fields (recreate branch)

- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaSchemaBuilder.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/model/embedded/Car.java
- graphql-jpa-query-schema/src/test/resources/data.sql
> fix: use embeddableType javaType to cache corresponding GraphQL type 

- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/IntrospectionUtils.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/StarwarsSchemaBuildTest.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/impl/IntrospectionUtilsTest.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/model/book/Book.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/model/calculated/CalculatedEntity.java
fix Issues #102 
When ever the `Entity` has methods that is `public` and have method name starting with `set` , building schema will fail. This version make a small change ( bypass check for read properties  ) so that build can pass.  
```
@Data
@Entity
public class Book {
@Id
Long id;
@GraphQLIgnoreOrder
@GraphQLIgnoreFilter
String title;
@ManyToOne(fetch=FetchType.LAZY)
Author author;
@Enumerated(EnumType.STRING)
Genre genre;
/**
* Method that have name start with "set" and have at least one arguments will Lead to Error on build time
* *Method* that doesn't have a argument won't give error
* *Method* that does not public won't give error
* @param i
*/
public void setSth(int i){
return;
}
}
```
> #102 fix NullPointerException when searching for Transient annotation

- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/QraphQLJpaBaseDataFetcher.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/GraphQLEnumVariableBindingsTests.java
Given variables json: 
```json
{
"genres": "NOVEL"
}
```
And the query with enum variable bindings:
```
query($genre: Genre) {
Books(where: {
genre: {EQ: $genre}
}) {
select {
id
title
genre
}
}
}
```
Will return:
```
{
"data": {
"Books": {
"select": [
{
"id": 2,
"title": "War and Peace",
"genre": "NOVEL"
},
{
"id": 3,
"title": "Anna Karenina",
"genre": "NOVEL"
}
]
}
}
}
```
And given variables json:
```json
{
"genres": ["NOVEL"]
}
```
And the query with enum list variable bindings:
```
query($genres: [Genre!]) {
Books(where: {
genre: {IN: $genres}
}) {
select {
id
title
}
}
}
```
will result: 
```
{
"data": {
"Books": {
"select": [
{
"id": 2,
"title": "War and Peace"
},
{
"id": 3,
"title": "Anna Karenina"
}
]
}
}
}
```
And given variables json:
```
{
"genre": "NOVEL"
}
```
And query with …
> feat: support enum variable bindings in queries

- .gitignore
- graphql-jpa-query-schema/pom.xml
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaOneToManyDataFetcher.java
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaSchemaBuilder.java
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/JpaPredicateBuilder.java
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/PredicateFilter.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/converter/GraphQLJpaConverterTests.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/converter/model/AbstractVariableEntity.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/converter/model/ActivitiEntityMetadata.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/converter/model/JsonEntity.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/converter/model/JsonNodeConverter.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/converter/model/ProcessVariableEntity.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/converter/model/TaskVariableEntity.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/converter/model/VariableValue.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/converter/model/VariableValueJsonConverter.java
- graphql-jpa-query-schema/src/test/resources/GraphQLJpaConverterTests.sql
Fixes #112 
This PR adds support for LOCATE predicate for JPA entity class attributes annotated with `@Convert`, i.e.
Given entity class with JsonNode attribute:
```java
@Entity(name = "JsonEntity")
@Table(name = "json_entity")
@Data
public class JsonEntity {
@Id
private int id;
private String firstName;
private String lastName;
@Convert(converter = JsonNodeConverter.class)
@Column(columnDefinition = "text")
private JsonNode attributes;
}
```
And JsonNodeConverter implementation:
```java
public class JsonNodeConverter implements AttributeConverter<JsonNode, String> {
private final static Logger logger = LoggerFactory.getLogger(JsonNodeConverter.class);
private static final ObjectMapper objectMapper = new ObjectMapper()
.disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES);
@Override …
```
> feat: add LOCATE predicate for JPA entity attributes annotated with @Convert

- graphql-jpa-query-example-merge/src/main/java/com/introproventures/graphql/jpa/query/example/books/Author.java
- graphql-jpa-query-example-merge/src/main/java/com/introproventures/graphql/jpa/query/example/books/Book.java
- graphql-jpa-query-example-merge/src/main/java/com/introproventures/graphql/jpa/query/example/starwars/Droid.java
- graphql-jpa-query-example-merge/src/main/java/com/introproventures/graphql/jpa/query/example/starwars/DroidFunction.java
- graphql-jpa-query-example-merge/src/main/resources/starwars.sql
- graphql-jpa-query-example/src/main/java/com/introproventures/graphql/jpa/query/example/model/DroidFunction.java
- graphql-jpa-query-example/src/main/java/com/introproventures/graphql/jpa/query/example/starwars/Droid.java
- graphql-jpa-query-example/src/main/java/com/introproventures/graphql/jpa/query/example/starwars/DroidFunction.java
- graphql-jpa-query-example/src/main/resources/data.sql
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaOneToManyDataFetcher.java
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaSchemaBuilder.java
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/QraphQLJpaBaseDataFetcher.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/GraphQLExecutorTests.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/StarwarsQueryExecutorTests.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/model/book/Author.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/model/book/Book.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/model/starwars/Droid.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/model/starwars/DroidFunction.java
- graphql-jpa-query-schema/src/test/resources/data.sql
Given the following query:
```
Authors(where: {
books: {
author: {
name: {LIKE: "Leo"}
}
}
}) {
select {
id
name
books {
id
title
genre
}
}
}
```
Expected result:
```
{
"data": {
"Authors": {
"select": [
{
"id": 1,
"name": "Leo Tolstoy",
"books": [
{
"id": 2,
"title": "War and Peace",
"genre": "NOVEL",
},
{
"id": 3,
"title": "Anna Karenina",
"genre": "NOVEL",
}
]
}
]
}
}
}
```
And collection filtering in nested relationships :
```
Books(where: {
title:{LIKE: "War"}
author: {
name:{LIKE: "Leo"}
books: {title: {LIKE: "Anna"}}
}
}) {
select {
id
title
genre
author {
id
name
books {
id
title
genre
}
}
}
}
```
Will return:
```
{
"data": {
"Books": {
"select": [
{
"id": 2,
"title": "War and Peace",
"genre": "NOVEL",
"author": {
"id": 1,
"name": "Leo Tolstoy",
"books": [
{
"id": 3,
"title": …
```
> feat: support nested relationships in where criteria expressions 

- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaSchemaBuilder.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/GraphQLExecutorSuperClassTests.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/model/book_superclass/BaseAuthor.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/model/book_superclass/BaseBook.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/model/book_superclass/SuperAuthor.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/model/book_superclass/SuperBook.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/model/book_superclass/SuperGenre.java
- graphql-jpa-query-schema/src/test/resources/hibernate.properties
This PR fixes class cast exception when mapping of `@MappedSuperclass` attribute from base class, i.e.
```
@ManyToOne(fetch= FetchType.LAZY)
SuperAuthor author;
```
> Fix  MappedSuperclass for JPA entity attributes

- .travis.yml
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/QraphQLJpaBaseDataFetcher.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/GraphQLExecutorTests.java
The PR fixes problem mapping GraphQL query with nested relation criteria expressions using nested AND: { OR: { expressions } } into JPQL, i.e.
```
query {
Authors(where: {
books: {
author: { name: {LIKE:"Leo"} }
AND: {
OR: {
id: {EQ: 2}
title: {LIKE: "Anna"}
}
}
}
}) {
select {
id
name
books {
id
title
genre
}
}
}
}  
```
Should produce the following Hibernate query:
```
select
author0_.id as id1_0_0_,
books1_.id as id1_2_1_,
author0_.genre as genre2_0_0_,
author0_.name as name3_0_0_,
books1_.author_id as author_i6_2_1_,
books1_.description as descript2_2_1_,
books1_.genre as genre3_2_1_,
books1_.publicationDate as publicat4_2_1_,
books1_.title as title5_2_1_,
books1_.author_id as author_i6_2_0__,
books1_.id as id1_2_0__ 
from
Author author0_ 
inner join
Book books1_ 
on …
```
> fix: compound nested relationship criteria expressions

- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/QraphQLJpaBaseDataFetcher.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/StarwarsQueryExecutorTests.java
Fixes  https://github.com/introproventures/graphql-jpa-query/issues/122
Given a query  with element collection attribute, i.e. `appearsIn`:
```
Characters (where: {
appearsIn :{IN: THE_FORCE_AWAKENS}
}) {
select {
id, 
name,
appearsIn
}
}
```
The result will contain all elements of `appearsIn` collection for each Character:
```
{
"data": {
"Characters": {
"select": [
{
"id": "1000",
"name": "Luke Skywalker",
"appearsIn": [
"A_NEW_HOPE",
"EMPIRE_STRIKES_BACK",
"RETURN_OF_THE_JEDI",
"THE_FORCE_AWAKENS"
]
},
{
"id": "1002",
"name": "Han Solo",
"appearsIn": [
"A_NEW_HOPE",
"EMPIRE_STRIKES_BACK",
"RETURN_OF_THE_JEDI",
"THE_FORCE_AWAKENS"
]
},
{
"id": "1003",
"name": "Leia Organa",
"appearsIn": [
"A_NEW_HOPE",
"EMPIRE_STRIKES_BACK",
"RETURN_OF_THE_JEDI",
"THE_FORCE_AWAKENS"
]
},
{
"id": "2000", …
```
> fix: lets fetch element collection attributes

- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaQueryDataFetcher.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/StarwarsQueryExecutorTests.java
Fixes https://github.com/introproventures/graphql-jpa-query/issues/118
> Let's pass and apply distinct in query results if enabled 

- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/JavaScalars.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/JavaScalarsTest.java
This PR adds support for generating Java Scalar type with default GraphQLObjectCoercing fallback for non-registered Java classes in JavaScalars type registry, i.e.
```java
// given
Class<?> clazz = VariableValue.class;
// when
GraphQLScalarType scalarType = JavaScalars.of(clazz);
// then
assertThat(scalarType.getCoercing()).isInstanceOf(GraphQLObjectCoercing.class);
assertThat(scalarType.getName()).isEqualTo("VariableValue");
```
> feat: Provide default GraphQLObjectCoercing fallback for non-existing Java classes

- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/JpaPredicateBuilder.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/converter/GraphQLJpaConverterTests.java
- graphql-jpa-query-schema/src/test/resources/GraphQLJpaConverterTests.sql
This PR adds support for `EQ` predicate with custom attribute types annotated with `@Convert`, i.e.
Given entity class with custom attribute:
```java
@Entity("TaskVariable")
public TaskVariableEntity {
@Id
@GeneratedValue(strategy = GenerationType.IDENTITY)
private Long id;
private String type;
private String name;
@Convert(converter = VariableValueJsonConverter.class)
@Column(columnDefinition="text")
private VariableValue<?> value;
}
```
And custom attribute value implementation with provided constructor having single Object argument :
```java
public class VariableValue<T> {
private T value;
public VariableValue() {
}
// Required constructor
public VariableValue(T value) {
this.value = value;
}
public T getValue() {
return value;
}
}    
```
And AttributeConverter class:
```java
public …
```
> feat: add equals criteria support for custom attributes types

- graphql-jpa-query-autoconfigure/src/main/java/com/introproventures/graphql/jpa/query/autoconfigure/GraphQLJpaQueryProperties.java
- graphql-jpa-query-autoconfigure/src/main/resources/com/introproventures/graphql/jpa/query/boot/autoconfigure/default.properties
- graphql-jpa-query-autoconfigure/src/test/java/com/introproventures/graphql/jpa/query/autoconfigure/GraphQLSchemaAutoConfigurationTest.java
- graphql-jpa-query-example-merge/src/main/java/com/introproventures/graphql/jpa/query/example/books/BooksSchemaConfiguration.java
- graphql-jpa-query-example-merge/src/main/resources/application.yml
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaQueryDataFetcher.java
This PR fixes GraphQLJPAQueryProperites.isDefaultDistinct typo and enables default distinct resolution configuration.
> fix: enable default distinct  configuration property

- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/JpaPredicateBuilder.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/converter/GraphQLJpaConverterTests.java
This PR add support for IN, NIN predicates in criteria expressions for custom attributes, i.e.
```
query {
TaskVariables(where: { 
value: {IN: [null, true, "data", 12345, 1.2345]} 
}) {
select {
name
value
}
}
}
```
```
query {
TaskVariables(where: { 
value: {NIN: true} 
}) {
select {
name
value
}
}
}
```
> feat: add IN | NIN predicate for custom attribute types

- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/JpaPredicateBuilder.java
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/QraphQLJpaBaseDataFetcher.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/GraphQLExecutorListCriteriaTests.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/GraphQLExecutorTests.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/StarwarsQueryExecutorTests.java
This PR builds a join fetch graph from query selection tree to avoid Hibernate error:  `query specified join fetching, but the owner of the fetched association was not present in the select list`
Given the following query:
```
{
Humans(where: {
friends: {
name: {LIKE: "R2-D2"}
}, 
favoriteDroid: {
primaryFunction: {
function: {EQ: "Protocol"}
}
}
}) {
select {
id
name
homePlanet
favoriteDroid {
name
primaryFunction {
function
}
}
friends {
name
friends {
name
}
}
}
}
}
```
The builder will traverse the selection graph to apply an explicit fetch join for each relation, after that it will reuse existing joins to apply where search criteria expressions. 
As a result the query will create a unique fetch join for each relation in the selection to fetch the related data and add where criteria …
> fix: build join fetch from selection graph

- graphql-jpa-query-autoconfigure/src/main/java/com/introproventures/graphql/jpa/query/autoconfigure/GraphQLJpaQueryProperties.java
- graphql-jpa-query-autoconfigure/src/test/java/com/introproventures/graphql/jpa/query/autoconfigure/GraphQLSchemaAutoConfigurationTest.java
- graphql-jpa-query-example-merge/src/main/resources/books.sql
- graphql-jpa-query-example-model-books/src/main/java/com/introproventures/graphql/jpa/query/schema/model/book/Genre.java
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaOneToManyDataFetcher.java
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaQueryDataFetcher.java
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaSchemaBuilder.java
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaSimpleDataFetcher.java
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/QraphQLJpaBaseDataFetcher.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/BooksSchemaBuildTest.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/GraphQLEnumVariableBindingsTests.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/GraphQLExecutorSuperClassTests.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/GraphQLExecutorTests.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/model/book_superclass/SuperGenre.java
- graphql-jpa-query-schema/src/test/resources/data.sql
This PR adds support for default `optional: true` argument for collections in the query selection graph, i.e.
```
query {
Authors {
select {
id
name
books(optional: true) {
id
title
genre
}
}
}
}
```
With `optional: true`, the data fetcher will apply LEFT OUTER JOIN on books and return empty books collections:
```
{
"data": {
"Authors": {
"select": [
{
"id": 1,
"name": "Leo Tolstoy",
"books": [
{
"id": 2,
"title": "War and Peace",
"genre": "NOVEL"
},
{
"id": 3,
"title": "Anna Karenina",
"genre": "NOVEL"
}
]
},
{
"id": 4,
"name": "Anton Chekhov",
"books": [
{
"id": 5,
"title": "The Cherry Orchard",
"genre": "PLAY"
},
{
"id": 6,
"title": "The Seagull",
"genre": "PLAY"
},
{
"id": 7,
"title": "Three Sisters",
"genre": "PLAY"
}
]
},
{
"id": 8,
"name": "Igor Dianov",
"books": []
}
]
}
}
}
``` …
> feat: add optional argument for plural attributes 

- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/JpaPredicateBuilder.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/converter/GraphQLJpaConverterTests.java
This PR adds support for NE predicates on custom attributes criteria expressions, i.e.
```
query {
TaskVariables(where: { 
value: {NE: null} 
}) {
select {
name
value
}
}
}
```
> feat: add NE predicate for custom attributes criteria  expressions

- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaOneToManyDataFetcher.java
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaSchemaBuilder.java
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/QraphQLJpaBaseDataFetcher.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/GraphQLEnumVariableBindingsTests.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/GraphQLExecutorTests.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/StarwarsQueryExecutorTests.java
This PR adds support for nested where criteria expressions, i.e. given query
```
query { 
Humans {        
select {
id
name
homePlanet
favoriteDroid {
name
primaryFunction(where:{function:{EQ:"Astromech"}}) {
function
}
}
}
}  
}
```
Will result in
```
{
"data": {
"Humans": {
"select": [
{
"id": "1001",
"name": "Darth Vader",
"homePlanet": "Tatooine",
"favoriteDroid": {
"name": "R2-D2",
"primaryFunction": {
"function": "Astromech"
}
}
}
]
}
}
}
```
> fix: add support for nested where criteria expressions

- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/JpaPredicateBuilder.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/StarwarsQueryExecutorTests.java
This PR fixes element collections fetch  sort order, i.e. given
```
{
Humans ( where: { 
appearsIn: {IN: [THE_FORCE_AWAKENS]}
}) { 
select { 
name 
appearsIn 
} 
}
}
```
Will result:
```
{
"data": {
"Humans": {
"select": [
{
"name": "Luke Skywalker",
"appearsIn": [
"A_NEW_HOPE",
"EMPIRE_STRIKES_BACK",
"RETURN_OF_THE_JEDI",
"THE_FORCE_AWAKENS"
]
},
{
"name": "Han Solo",
"appearsIn": [
"A_NEW_HOPE",
"EMPIRE_STRIKES_BACK",
"RETURN_OF_THE_JEDI",
"THE_FORCE_AWAKENS"
]
},
{
"name": "Leia Organa",
"appearsIn": [
"A_NEW_HOPE",
"EMPIRE_STRIKES_BACK",
"RETURN_OF_THE_JEDI",
"THE_FORCE_AWAKENS"
]
}
]
}
}
}
```
> fix: correct element collection fetch sort order

- graphql-jpa-query-web/src/main/java/com/introproventures/graphql/jpa/query/web/autoconfigure/GraphQLControllerAutoConfiguration.java
- graphql-jpa-query-web/src/test/java/com/introproventures/graphql/jpa/query/web/autoconfigure/GraphQLControllerAutoConfigurationPropertyDisabledTest.java
- graphql-jpa-query-web/src/test/java/com/introproventures/graphql/jpa/query/web/autoconfigure/GraphQLControllerAutoConfigurationWebPropertyDisabledTest.java
This PR adds support to disable GraphQLController auto configuration using `spring.graphql.jpa.query.web.enabled` property. The auto configuration will also be disabled if `spring.graphql.jpa.query.enabled=false` 
Fixes https://github.com/introproventures/graphql-jpa-query/issues/144
> feat: add conditional property to disable GraphQLController

- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/QraphQLJpaBaseDataFetcher.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/GraphQLWhereVariableBindingsTests.java
@igdianov I've added here my test case and one fix for your solution. However I am not sure if my creation of yet another PR for the issue is correct. Shouldn't we maintain it in the single one?
> Where variable binding implementation

- graphql-jpa-query-annotations/src/main/java/com/introproventures/graphql/jpa/query/annotation/GraphQLIgnore.java
- graphql-jpa-query-example-model-books/src/main/java/com/introproventures/graphql/jpa/query/schema/model/book/Book.java
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaSchemaBuilder.java
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/IntrospectionUtils.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/CalculatedEntityTests.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/GraphQLExecutorTests.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/impl/IntrospectionUtilsTest.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/model/calculated/CalculatedEntity.java
Fixes #153 by adding METHOD to annotation target, so given `@GraphQLIgnore` annotation
```java
@Target( { TYPE, FIELD, METHOD })
@Retention(RUNTIME)
public @interface GraphQLIgnore {
}
```
can be applied on getter methods in entity class to exclude these properties from schema mapping, i.e.:
```java
@Data
@Entity
@EqualsAndHashCode(exclude="author")
public class Book {
@Id
Long id;
String title;
@ManyToOne(fetch=FetchType.LAZY, optional = false)
Author author;
@Transient
@GraphQLIgnore
public String getAuthorName(){
return author.getName();
}
}
```
> Add METHOD to the @GraphQLIgnore annotation target

- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/QraphQLJpaBaseDataFetcher.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/GraphQLExecutorTests.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/GraphQLWhereVariableBindingsTests.java
This PR adds support for variable where criteria expressions, i.e. given
```
query($where: BooksCriteriaExpression) {
Books (where: $where) {
select {
id(orderBy: ASC)
title
genre
}
}
}
```
with variables payload:
```
{
"where": { 
"genre": {
"IN": ["NOVEL"]
}
}
}
```
the expected result will be:
```
{
"data": {
"Books": {
"select": [
{
"id": 2,
"title": "War and Peace",
"genre": "NOVEL"
},
{
"id": 3,
"title": "Anna Karenina",
"genre": "NOVEL"
}
]
}
}
}
```
Fixes https://github.com/introproventures/graphql-jpa-query/issues/126
> feat: add support for variable where criteria expressions

- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaSchemaBuilder.java
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/IntrospectionUtils.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/CalculatedEntityTests.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/impl/IntrospectionUtilsTest.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/model/calculated/CalculatedEntity.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/model/calculated/ParentCalculatedEntity.java
This PR adds support for mapping entity fields that use Java `transient` modifier JPA transient fields mapping specification, i.e.
```java
@MappedSuperclass
public class ParentCalculatedEntity {
private transient String parentTransientModifier; // transient property
}
```
```java
@Data
@EqualsAndHashCode(callSuper = true)
@Entity
public class CalculatedEntity extends ParentCalculatedEntity {
private transient Integer transientModifier; // transient property
}
```
The transient Java fields can be excluded from schema using `@GraphQLIgnore` annotation.
> feat: add support for mapping transient fields with entity class hierarchy introspection

- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/CalculatedEntityTests.java
@igdianov I've added test case that I had created for the description inheritance issue
> Add test case that validates schema after it is created

- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/IntrospectionUtils.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/impl/IntrospectionUtilsTest.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/model/calculated/CalculatedEntity.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/model/calculated/ParentCalculatedEntity.java
Additional introspection test cases
> Add duplicated property test case

- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/IntrospectionUtils.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/CalculatedEntityTests.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/impl/IntrospectionUtilsTest.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/model/calculated/CalculatedEntity.java
Fixes https://github.com/introproventures/graphql-jpa-query/issues/174
> fix: add test case for private getter 

- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaQueryDataFetcher.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/idclass/EntityWithIdClassTest.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/idclass/model/Account.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/idclass/model/AccountId.java
- graphql-jpa-query-schema/src/test/resources/EntityWithIdClassTest.sql
Fixes https://github.com/introproventures/graphql-jpa-query/issues/176
> fix: Error querying entity with @IdClass #176

- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/JpaPredicateBuilder.java
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/QraphQLJpaBaseDataFetcher.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/embeddedid/EntityWithEmbeddedIdTest.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/embeddedid/model/Book.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/embeddedid/model/BookId.java
- graphql-jpa-query-schema/src/test/resources/EntityWithEmbeddedIdTest.sql
This PR adds query support for entitites with `@EmbeddedId` attributes, i.e. given:
```java
@Data
@Entity
public class Book {
@EmbeddedId
private BookId bookId;
private String description;
} 
```
with embedded id attribute
```java
@Data
@Embeddable
public class BookId implements Serializable {
private static final long serialVersionUID = 1L;
private String title;
private String language;
} 
```
then, use query with embedded id:
```
query {
Books( 
where: {
bookId: {
EQ: {
title:  "War and Piece"
language:  "Russian"
}
}
}
){
total
pages
select {
bookId {
title
language
}
description
}
}
}
```
> fix: add query support for entities with `@EmbeddedId` attribute

- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/JpaPredicateBuilder.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/GraphQLExecutorTests.java
Fixes https://github.com/introproventures/graphql-jpa-query/issues/185
> fix: switch off lower(COLUMN_NAME) decoration on String equality check

- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaQueryDataFetcher.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/GraphQLExecutorTests.java
This PR removes calling EntityManager.clear() inside GraphQLJpaQueryDataFetcher.get() that causes runtime NPE in Hibernate in order to fix https://github.com/introproventures/graphql-jpa-query/issues/191 
The `EntityManager.clear()` has been added in this commit: https://github.com/introproventures/graphql-jpa-query/pull/96/commits/83c5a84648c8a0a0f566874a6cea78bee2a521ed because of the mentioned problem: https://github.com/introproventures/graphql-jpa-query/pull/96#issuecomment-472544018
The provided test case cannot reproduce the issue anymore: 9e5002bc760e9420f1bcb64726129cea20ed6582
Calling clear method seems to be very invasive, since there are hints provided for Hibernate not to cache any results in memory: https://github.com/introproventures/graphql-jpa-query/blob/7ce947d72b9dc6ce0e …
> fix: removed EntityManager.clear() from GraphQLJpaQueryDataFetcher

- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaSchemaBuilder.java
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/QraphQLJpaBaseDataFetcher.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/GraphQLExecutorTests.java
> Add fix and test case for orderBy argument as a variable

- graphql-jpa-query-example-merge/src/main/resources/books.sql
- graphql-jpa-query-example-model-books/src/main/java/com/introproventures/graphql/jpa/query/schema/model/book/Book.java
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/QraphQLJpaBaseDataFetcher.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/GraphQLExecutorTests.java
- graphql-jpa-query-schema/src/test/resources/data.sql
This PR fixes fetching plural attributes annotated with `@ElementCollection` to use left outer join that makes collection elements optional should associated collection elements data set be empty, i.e. given
```java
public class Author {
@Id
Long id;
String name;
@OneToMany(mappedBy="author", fetch=FetchType.LAZY)
@OrderBy("id ASC")
Set<Book> books;
@ElementCollection(fetch=FetchType.LAZY) 
@CollectionTable(name = "author_phone_numbers", joinColumns = @JoinColumn(name = "author_id")) 
@Column(name = "phone_number")
private Set<String> phoneNumbers = new HashSet<>();	
@Enumerated(EnumType.STRING)
Genre genre;	
}
``` 
When executing the following query with author containing empty `phoneNumbers` selection:
```
query {
Author(id: 8) {
id
name
phoneNumbers
books {
id
title
tags
}
}
}
```
The …
> fix(GH-198): adedd support for fetching optional element collections elements

- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaQueryDataFetcher.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/GraphQLExecutorTests.java
Fixes https://github.com/introproventures/graphql-jpa-query/issues/193
> fix(GH-193): Fixed error in GQL Queries when `total` or `pages` is included with condition `where: NOT_EXISTS` or `EXISTS`

- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaQueryDataFetcher.java
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaSimpleDataFetcher.java
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/QraphQLJpaBaseDataFetcher.java
This PR removes redundant entity graph hint causing duplicate joins on the same tables. 
Fixes https://github.com/introproventures/graphql-jpa-query/issues/216
Given GraphQL query:
```
query { 
Humans(where:{id:{EQ: "1000"}}) {
select {
name, homePlanet, friends { name } 
}
}
}
```
Then generated JPQL query
```
select distinct human 
from Human as human left join fetch human.friends as generatedAlias0 
where human.id=:param0 order by human.id asc
```
is transformed by Hibernate into SQL query:
```
select
human0_.id as id2_0_0_,
character2_.id as id2_0_1_,
human0_.name as name3_0_0_,
human0_.favorite_droid_id as favorite6_0_0_,
human0_.gender_code_id as gender_c7_0_0_,
human0_.homePlanet as homePlan4_0_0_,
character2_.name as name3_0_1_,
character2_.primary_function as primary_5_0_1_, …
```
> fix(GH-216): One-to-many queries joins the same tables twice 

- graphql-jpa-query-example-model-starwars/src/main/java/com/introproventures/graphql/jpa/query/schema/model/starwars/Character.java
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaQueryDataFetcher.java
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaSchemaBuilder.java
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/JpaPredicateBuilder.java
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/QraphQLJpaBaseDataFetcher.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/GraphQLExecutorListCriteriaTests.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/GraphQLExecutorTests.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/StarwarsQueryExecutorTests.java
This PR fixes the query and mapping problem with nested recursive queries in where search criterias with `@ManyToMany` mapping on Character entity.  
For example, when mapping "author" / "book" as many-to-many, we need "authors" collection on Book and "books" collection on Author. In our case,  "Character" entity represents both ends of a relationship; so we need "friends to" and "friend of" collections. 
We can still use the same association table, but note that friendsOf is mappedBy `friends`. 
```java
@Entity
@GraphQLDescription("Abstract representation of an entity in the Star Wars Universe")
@Getter
@Setter
@ToString
@EqualsAndHashCode(exclude={"appearsIn","friends", "friendsOf"}) // Fixes NPE in Hibernate when initializing loaded collections #1
public abstract class Character {
@Id …
```
> fix(GH-220): Cannot nest multiple queries on the same table

- graphql-jpa-query-example-merge/src/main/java/com/introproventures/graphql/jpa/query/example/books/BooksSchemaConfiguration.java
- graphql-jpa-query-example-merge/src/main/java/com/introproventures/graphql/jpa/query/example/starwars/StarwarsSchemaConfiguration.java
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaExecutor.java
Fixes https://github.com/introproventures/graphql-jpa-query/issues/225
As described in https://docs.jboss.org/hibernate/core/4.0/hem/en-US/html/transactions.html#transactions-basics-issues Never use the anti-patterns entitymanager-per-user-session or entitymanager-per-application (of course, there are rare exceptions to this rule, e.g. entitymanager-per-application might be acceptable in a desktop application, with manual flushing of the persistence context). Note that some of the following issues might also appear with the recommended patterns, make sure you understand the implications before making a design decision:
* An entity manager is not thread-safe. Things which are supposed to work concurrently, like HTTP requests, session beans, or Swing workers, will cause race conditions if …
> fix(GH-225): Configure shared entity manager for multiple data sources example

- graphql-jpa-query-example-merge/src/main/resources/application.yml
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaQueryDataFetcher.java
- graphql-jpa-query-schema/src/test/resources/application.properties
Fixes https://github.com/introproventures/graphql-jpa-query/issues/226
Configured by DEBUG logging level on `com.introproventures.graphql.jpa.query.schema` package.
```
logging:
level:
com.introproventures.graphql.jpa.query.schema: DEBUG
```
Then, log output will produce:
```
2019-12-14 17:27:36.865  INFO 5868 --- [nio-8080-exec-8] c.i.g.j.q.s.i.GraphQLJpaQueryDataFetcher : 
GraphQL JPQL Query String:
select distinct droid from Droid as droid left join fetch droid.friends as generatedAlias0 left join fetch generatedAlias0.friendsOf as generatedAlias1 where generatedAlias1.name=:param0 order by droid.id asc
```
> feat(GH-226): Support logging of the generated JPQL query string with debug log level 

- graphql-jpa-query-build/pom.xml
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/AbstractSpringBootTestSupport.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/converter/GraphQLJpaConverterTests.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/embeddedid/EntityWithEmbeddedIdTest.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/idclass/EntityWithIdClassTest.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/localdatetime/GraphQLLocalDateTimeTest.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/BooksSchemaBuildTest.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/CalculatedEntityTests.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/EntityIntrospectorTest.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/GraphQLEnumVariableBindingsTests.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/GraphQLExecutorListCriteriaTests.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/GraphQLExecutorSuperClassTests.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/GraphQLExecutorTests.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/GraphQLWhereVariableBindingsTests.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/StarwarsQueryExecutorTests.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/StarwarsSchemaBuildTest.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/StarwarsSchemaBuildWithDistinctTest.java
- graphql-jpa-query-schema/src/test/resources/hibernate.properties
- pom.xml
This PR upgrades build configuration to use SB 2.1.11.RELEASE. 
The upgraded Hibernate version now needs to have JDBC timezone to match JVM timezone to support queries with Java `Date` type attributes. 
See for details: https://in.relation.to/2016/09/12/jdbc-time-zone-configuration-property/
> fix(versions): upgrade spring-boot-dependencies to 2.1.11.RELEASE

- graphql-jpa-query-autoconfigure/pom.xml
- graphql-jpa-query-autoconfigure/src/main/java/com/introproventures/graphql/jpa/query/autoconfigure/GraphQLSchemaFactoryBean.java
- graphql-jpa-query-autoconfigure/src/test/java/com/introproventures/graphql/jpa/query/autoconfigure/GraphQLSchemaAutoConfigurationTest.java
- graphql-jpa-query-autoconfigure/src/test/java/com/introproventures/graphql/jpa/query/autoconfigure/support/AdditionalGraphQLType.java
- graphql-jpa-query-autoconfigure/src/test/java/com/introproventures/graphql/jpa/query/autoconfigure/support/MutationRoot.java
- graphql-jpa-query-autoconfigure/src/test/java/com/introproventures/graphql/jpa/query/autoconfigure/support/QueryRoot.java
- graphql-jpa-query-autoconfigure/src/test/java/com/introproventures/graphql/jpa/query/autoconfigure/support/SubscriptionRoot.java
- graphql-jpa-query-boot-starter/src/test/java/com/introproventures/graphql/jpa/query/starter/GraphQLJpaQueryStarterIT.java
- graphql-jpa-query-dependencies/pom.xml
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/JavaScalars.java
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/DataFetchingEnvironmentBuilder.java
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaExecutor.java
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaQueryDataFetcher.java
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaSchemaBuilder.java
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaSimpleDataFetcher.java
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/QraphQLJpaBaseDataFetcher.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/converter/GraphQLJpaConverterTests.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/GraphQLExecutorTests.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/JavaScalarsTest.java
This PR is a fork from https://github.com/introproventures/graphql-jpa-query/pull/205 that adds  the following changes to original commit:
* refactor: added DataFetchingEnvironmentBuilder wrapper class …
* refactor(JavaScalars): Renamed method toScalarType to newScalarType
* fix: Resolved NPE with nullable arguments in GraphQLJpaExecutor.execute
* polish: Replaced NullValue builder() with `NullValue.Null`instance
* refactor: Removed ExecutionResult implementation from GraphQLJpaQueryStarterIT
* feat: added support to merge CodeRegistries
* feat: added test example for graphql-java-annotations library
> Upgrade graphql-java version to 13.0 

- graphql-jpa-query-example-merge/src/main/java/com/introproventures/graphql/jpa/query/example/Application.java
- graphql-jpa-query-example-model-books/src/main/java/com/introproventures/graphql/jpa/query/schema/model/book/Book.java
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaExecutorContext.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaExecutorContextFactoryTest.java
> fix(GH-239): Added GraphQLFieldVisibility supplier support in GraphQL request

- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaSchemaBuilder.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/BooksSchemaBuildTest.java
This PR  adds support to configure list of entities with matching entity class path prefixes to be included in the result schema, i.e.
```java
@Bean
public GraphQLSchemaBuilder graphQLSchemaBuilder(EntityManager entityManager) {
return new GraphQLJpaSchemaBuilder(entityManager)
.name("BooksExampleSchema")
.entityPath(Book.class.getName())
.entityPath(Author.class.getName())
.entityPath(Thing.class.getPackageName())
.description("Books Example Schema");
}
```
Fixes #224
> feat(GH-224): Added support for entity path class name prefix in GraphQLJpaSchemaBuilder

- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaExecutorContext.java
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaQueryDataFetcher.java
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaSchemaBuilder.java
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/relay/GraphQLJpaRelayDataFetcher.java
This PR adds support to enable/disable default max result size query pagination via GraphQLJpaSchemaBuilder.enableDefaultMaxResultSize(boolean) feature toggle. This feature is enabled by default.
Fixes #253
> fix(GH-253): Support enable/disable default max result size query pagination

- graphql-jpa-query-boot-starter/src/main/java/com/introproventures/graphql/jpa/query/boot/autoconfigure/GraphQLJpaQueryAutoConfiguration.java
This PR fixes exception when using graphql-jpa with leangen
Fixes #249
> fix(GH-249): Resolve exception when using graphql-jpa with leangen

- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/JavaScalars.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/JavaScalarsTest.java
> fix(GH-232):  SimpleDateFormat is not threadsafe

- graphql-jpa-query-graphiql/src/main/resources/static/graphiql/index.html
This PR adds support for custom server servlet context path configuration in parent Spring Boot Application.
> fix: add support for server.servlet.content-path configuration

- graphql-jpa-query-boot-starter/src/main/java/com/introproventures/graphql/jpa/query/boot/autoconfigure/GraphQLJpaQueryAutoConfiguration.java
- graphql-jpa-query-boot-starter/src/test/java/com/introproventures/graphql/jpa/query/boot/test/boot/autoconfigure/GraphQLJpaQueryAutoConfigurationTest.java
- graphql-jpa-query-schema/pom.xml
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/RestrictedKeysProvider.java
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaQueryDataFetcher.java
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaQueryFactory.java
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaSchemaBuilder.java
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/relay/GraphQLJpaRelayDataFetcher.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/restricted/RestrictedKeysProviderRelayTests.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/restricted/RestrictedKeysProviderSelectTests.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/restricted/RestrictedKeysProviderTests.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/restricted/SpringSecurityRestrictedKeysProvider.java
- graphql-jpa-query-schema/src/test/resources/RestrictedKeysProviderTests.sql
This PR adds support for row filtering via restricting query search criteria using pluggable RestrictedKeysProvider implementation.
The RestrictedKeysProvider functional interface should provide a list of restricted keys in order to filter records  at runtime based on user security context and supplied EntityIntrospection descriptor arugment.  
The return argument uses Optional<List<Object>> return type.  
* The non-empty list will restrict the query results to provided keys 
* The empty list will execute the query without any restrictions.  
* The empty Optional will block running the query and return empty result list or null value.  
```java
@FunctionalInterface
public interface RestrictedKeysProvider extends Function<EntityIntrospectionResult, Optional<List<Object>>> {
/**
* Applies …
```
> feat: add initial support for restricted keys query provider implementation

- graphql-jpa-query-example-simple/src/main/resources/application.yml
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaQueryFactory.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/StarwarsQueryExecutorTests.java
> fix(GH-273): detach result entities from entity manager persistent context

- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/JavaScalars.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/JavaScalarsTest.java
This PR adds support for parsing and serializing Timestamp scalar value, i.e.
The output of serialize is a string in ISO 8086 Date/Time in UTC time zone, i.e. "2019-08-05T07:15:07Z"
The output of parseValue and parseLiteral is java.sql Timestamp value in UTC time zone.
> fix: add support for java.sql.Timestamp GraphQLScalar coercing

- graphql-jpa-query-boot-starter/src/main/java/com/introproventures/graphql/jpa/query/boot/autoconfigure/GraphQLJpaQueryAutoConfiguration.java
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaExecutorContext.java
- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaExecutorContextFactory.java
I wanted to specify my own DataFetcherExceptionHandler so here we are to allow define custom ExecutionStrategies.
> Make execution strategies configurable

- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/JpaPredicateBuilder.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/converter/GraphQLJpaConverterTests.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/converter/model/TaskEntity.java
- graphql-jpa-query-schema/src/test/resources/GraphQLJpaConverterTests.sql
Add support for types to build EQ/NE predicates for Java scalars with `null` values
- Boolean.class
- Byte.class
- Character.class
- Double.class
- Float.class
- Integer.class
- Long.class
- Short.class
- BigInteger.class
- BigDecimal.class
- String.class
- Date.class
- LocalDate.class
- LocalDateTime.class
- ZonedDateTime.class
- Instant.class
- LocalTime.class
- Calendar.class
- OffsetDateTime.class
- java.sql.Date.class
- java.sql.Time.class
- java.sql.Timestamp.class
- UUID.class
See tests for details..
> fix: support EQ/NE nullable criteria values  for Java scalars

- graphql-jpa-query-schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaSchemaBuilder.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/embeddedid/EntityWithEmbeddedIdTest.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/GraphQLExecutorTests.java
- graphql-jpa-query-schema/src/test/java/com/introproventures/graphql/jpa/query/schema/model/embedded/Engine.java
- graphql-jpa-query-schema/src/test/resources/data.sql
lets consider an example:
we have an entity with `@Embedded` field
embedded field contains a long value
we want to make query where embedded.longVal > 7
but unfortunately there was no way to do so, because if we do where query with:
`embedded: {GT: {longVal: 7}}`
we will get an exception.
`Unsupported field type class <className> for field <embeddedField>`
this PR changes schema generation for embedded and allows for such queries to be performed.
(query will look like: `embedded: {longVal: {GT: 7}}`)
> bugfix: query with embedded entity producing an exception

- graphql-jpa-query-autoconfigure/src/main/java/com/introproventures/graphql/jpa/query/autoconfigure/GraphQLSchemaAutoConfiguration.java
- graphql-jpa-query-autoconfigure/src/main/java/com/introproventures/graphql/jpa/query/autoconfigure/GraphQLSchemaBuilderAutoConfiguration.java
- graphql-jpa-query-autoconfigure/src/main/java/com/introproventures/graphql/jpa/query/autoconfigure/GraphQLShemaRegistration.java
This PR fixes default GraphQLSchemaConfigurer bean race condition in autoconfigure where Spring Boot ConditionalOnMissingBean missed existing GraphQLSchemaConfigurer beans in the application context.
> fix: resolve default GraphQLSchemaConfigurer bean race condition in autoconfigure

- annotations/pom.xml
- autoconfigure/pom.xml
- boot-starter/pom.xml
- build/pom.xml
- dependencies/pom.xml
- examples/pom.xml
- examples/spring-graphql-web/pom.xml
- introspection/pom.xml
- pom.xml
- scalars/pom.xml
- schema/pom.xml
- schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaQueryFactory.java
- schema/src/test/java/com/introproventures/graphql/jpa/query/schema/StarwarsQueryExecutorTests.java
- schema/src/test/java/com/introproventures/graphql/jpa/query/support/StarwarsQueryExecutorTestsSupport.java
- tests/boot-starter/pom.xml
- tests/models/books/pom.xml
- tests/models/pom.xml
- tests/models/starwars/pom.xml
- tests/multiple-datasources/pom.xml
- tests/pom.xml
- tests/relay/pom.xml
- tests/starwars/pom.xml
- tests/web/pom.xml
- web/pom.xml
> Update dependencies to Spring Boot 3.1.0

- autoconfigure/pom.xml
- autoconfigure/src/main/java/com/introproventures/graphql/jpa/query/autoconfigure/GraphQLJpaQueryAutoConfiguration.java
- autoconfigure/src/main/java/com/introproventures/graphql/jpa/query/autoconfigure/GraphQLJpaQueryGraphQlSourceAutoConfiguration.java
- autoconfigure/src/main/java/com/introproventures/graphql/jpa/query/autoconfigure/GraphQLSchemaBuilderAutoConfiguration.java
- autoconfigure/src/main/java/com/introproventures/graphql/jpa/query/autoconfigure/GraphQLSchemaEntityManager.java
- autoconfigure/src/main/java/com/introproventures/graphql/jpa/query/autoconfigure/GraphQLSchemaTransactionTemplate.java
- autoconfigure/src/main/java/com/introproventures/graphql/jpa/query/autoconfigure/MutationExecutionStrategyProvider.java
- autoconfigure/src/main/java/com/introproventures/graphql/jpa/query/autoconfigure/QueryExecutionStrategyProvider.java
- autoconfigure/src/main/java/com/introproventures/graphql/jpa/query/autoconfigure/SubscriptionExecutionStrategyProvider.java
- autoconfigure/src/main/java/com/introproventures/graphql/jpa/query/autoconfigure/TransactionalDelegateExecutionStrategy.java
- autoconfigure/src/test/java/com/introproventures/graphql/jpa/query/autoconfigure/GraphQLSchemaAutoConfigurationTest.java
- schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaExecutor.java
- schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaQueryFactory.java
- schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaSchemaBuilder.java
- schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaToManyMappedBatchLoader.java
- schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaToOneMappedBatchLoader.java
- schema/src/test/java/com/introproventures/graphql/jpa/query/converter/GraphQLJpaConverterTests.java
- tests/multiple-datasources/src/main/java/com/introproventures/graphql/jpa/query/example/Application.java
- web/src/main/java/com/introproventures/graphql/jpa/query/web/GraphQLController.java
To fix intermittent incorrect empty query results due to Hibernate query result list containing proxied entities when executing query requests concurrently.  
The GraphQLJPAQueryBuilder was not using the Shared Entity Manager proxy provided by Spring ORM. Instead, it was configured using a static instance backed by non-thread safe Hibernate Session created by the entity manager factory method.
A Spring shared EntityManager will behave just like an EntityManager fetched from an application server's JNDI environment, as defined by the JPA specification. It will delegate all calls to the current transactional EntityManager already attached to a thread per transaction, if any; otherwise it will fall back to a newly created EntityManager per operation request.
The functional tests worked fine, …
> Fix auto-configuration to apply a shared container entity manager instance for GraphQLJPASchemaBuilder 

- build/pom.xml
- dependencies/pom.xml
- schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaQueryFactory.java
> Upgrade Spring Boot version to 3.2.0

- dependencies/pom.xml
Remove hibernate-core from graphql-jpa-query-dependencies managed dependencies
> Remove hibernate-core from graphql-jpa-query-dependencies managed dependencies

- schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaQueryFactory.java
- schema/src/test/java/com/introproventures/graphql/jpa/query/converter/GraphQLJpaConverterTests.java
- tests/gatling/src/main/resources/data.sql
```graphql
query {
Tasks(
where: {
status: { EQ: COMPLETED }
AND: [
{ variables: { name: { EQ: "variable1" }, value: { EQ: "data" } } }
{ variables: { name: { EQ: "variable2" }, value: { EQ: true } } }
]
}
) {
select {
id
status
variables {
name
value
}
}
}
}
```
> Fix where query criteria with multiple associations joins

- pom.xml
- schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/EntityIntrospector.java
- schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaQueryDataFetcher.java
- schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaQueryFactory.java
- schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaSchemaBuilder.java
- schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/PagedResult.java
- schema/src/main/java/com/introproventures/graphql/jpa/query/support/GraphQLSupport.java
- schema/src/test/java/com/introproventures/graphql/jpa/query/converter/GraphQLJpaQueryAggregateTests.java
- schema/src/test/resources/GraphQLJpaAggregateTests.sql
- tests/gatling/src/main/java/com/introproventures/graphql/jpa/query/example/Application.java
Added an optional feature to generate aggregate count query for plural entities object types. The aggregate feature can be enabled on GraphQLSchemaBuilderCustomizer:
```java
@Bean
GraphQLJPASchemaBuilderCustomizer graphQLJPASchemaBuilderCustomizer() {
return builder ->
builder
.name("Query")
.enableAggregate(true);
});
```
The GraphQL Schema builder will generate `aggregate` selection field to be able to request counts. The count can be grouped by entity fields and nested associations, i.e.
```graphql
query {
Tasks {
aggregate {
countTasks: count
countProcessVariables: count(of: processVariables)
countTaskVariables: count(of: variables)
countTasksGroupedByStatus: group {
status: by(field: status)
count
}
countProcessVariablesGroupedByTaskName: group {
name: by(field: name)
count(of: …
```
> Add optional feature for aggregate count query support on plural entity object types

- schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaQueryDataFetcher.java
- schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaSchemaBuilder.java
- schema/src/test/java/com/introproventures/graphql/jpa/query/converter/GraphQLJpaQueryAggregateTests.java
Move all aggregate queries for nested aggregations into dedicated `by` field to improve schema definition and data fetching for further extension, i.e.
Before:
```graphql
query {
TaskVariables(
where: {name: {IN: ["variable1", "variable5"]}}
) {
aggregate {
task {
by(field: status)
count
}
}
}
}
```
After 
```graphql
query {
TaskVariables(
where: {name: {IN: ["variable1", "variable5"]}}
) {
aggregate {
by {
task {
by(field: status)
count
}
}
}
}
}
```
> Extract aggregate query fields for nested associations into dedicated by field

- schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaQueryFactory.java
- schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaSchemaBuilder.java
- schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/Logical.java
- schema/src/test/java/com/introproventures/graphql/jpa/query/support/GraphQLExecutorTestsSupport.java
For #243 
Still testing this implementation some more on my own end within the projects I have just to confirm its doing exactly what I would expect, but the initial unit test results are promising.
> Add logical NOT support

- schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/GraphQLJpaQueryDataFetcher.java
- schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/PagedResult.java
- schema/src/main/java/com/introproventures/graphql/jpa/query/schema/impl/ResultStreamWrapper.java
Skip executing redundant paged fetch query that does not have any results, i.e.
```graphql
query tasksWithMultipleProcessVariables {
Tasks(page: {limit : {Int}, start : {Int}}, where: {status : {IN : [CREATED]}, AND : [{processVariables : {name : {EQ : {String}}, value : {EQ : {String}}}}, {name : {LIKE : {String}}}]}) {
total
pages
select {
id
processInstanceId
assignee
status
candidateGroups
createdDate(orderBy: ASC)
processVariables(where: {name : {IN : [{String}]}}) {
name
type
value
}
}
}
}
```
The first generated SQL query fetches task keys with the empty result, i.e.
```
select te1_0.id 
from task te1_0 
left join task_process_variable pv1_0 on te1_0.id = pv1_0.task_id 
left join process_variable pv1_1 on pv1_1.id = pv1_0.process_variable_id 
where pv1_1.name = ? and pv1_1. value = …
```
> Skip redundant fetch query for empty query keys results

- scalars/src/main/java/com/introproventures/graphql/jpa/query/schema/JavaScalars.java
- scalars/src/test/java/com/introproventures/graphql/jpa/query/schema/JavaScalarsTest.java
by raising `CoersingParseValueException` with detailed message for troubleshooting
> Fix NPE when parsing invalid timestamp variable inputs
